//Add your Fluent APIs here and in other now.ts files under src/fluent
import './roles/user.now'
import './roles/agent.now'
import './roles/admin.now'
import './tables/event-request.now'
import './tables/room.now'
import './tables/event.now'
import './acls/event-request-admin.now'
import './acls/event-request-agent.now'
import './acls/event-request-user.now'
import './acls/room-admin.now'
import './acls/room-user.now'
import './acls/event-admin.now'
import './acls/event-agent.now'
import './acls/event-user.now'